version: '2'

services:
  agent-user:
    build: 
      context: .
      dockerfile: ./agent/Dockerfile
    hostname: payment
    command: bash -c "cd target && java -jar microVerumAgentProxy-0.0.1-SNAPSHOT-jar-with-dependencies.jar  80 user 80 microverum-db 27017 sync"
    depends_on:
      - "microverum-db"


  microverum-db:
    image: mongo:3.4
    hostname: microverum-db
    restart: always
