version: '2'


services:

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    ports:
      - "9999:80"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    depends_on:
      - "agent-catalogue"


  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb

  agent-catalogue:
    build: 
      context: .
      dockerfile: ./agent/Dockerfile
    hostname: agent-catalogue
    ports:
      - "8888:80"
    command: bash -c "mvn exec:java -Dlocal.port=80 -Dservice.address=catalogue -Dservice.port=80 -Dmicro.verum.log.address=microverum-db"
    depends_on:
      - "microverum-db"



  microverum-db:
    image: mongo:3.4
    hostname: microverum-db
    restart: always

  jmeter:
    image: justb4/jmeter:3.3
    hostname: jmeter
    restart: always