version: '2'

services:

  nginx:
    image: nginx:stable-alpine
    hostname: nginx
    ports:
      - 8888:80
  agent-nginx:
    build: 
      context: .
      dockerfile: ./microVerumAgent/Dockerfile
    hostname: agent- nginx
    ports:
      - "80:80"
      - "443:443"
    command: bash -c "./mvnw spring-boot:run -Dspring-boot.run.arguments=nginx,80"
    depends_on:
      - "microverum-db"
      - "microverum-admin-console"



  microverum-admin-console:
    build: 
      context: .
      dockerfile: ./microVerumAdminConsole/Dockerfile
    hostname: microverum-admin-console
    command: bash -c "./mvnw spring-boot:run"
    depends_on:
      - "microverum-db"



  microverum-db:
    image: mongo:3.4
    hostname: microverum-db
    restart: always


